### ISSUE TITLE
大佬，模型替换也分享一下咯？ 

### ISSUE THREAD

**Issue by mc112611** [Airmomo/graphrag-practice-chinese#1]
1.本地加载

2.部署服务提供API

在readme里面使用GLM系列，给一下调用方式咯。

**Comment by Airmomo** [comment]
@mc112611 ：

😃我重新修改了我的Readme内容，并补充上传了我的配置文件。
重新拉取项目后，在项目根目录你可以找到作为参考的配置文件 `demo.env` 和 `settings.demo.yaml`。
你可以作为参考配置修改，也可以通过重命名覆盖初始化的配置文件。

GLM系列模型的调用（模型替换）：
主要是通过修改`settings.demo.yaml`文件中对`llm`和`embeddings`的配置，使其使用智谱AI提供的API，主要修改的字段有`api_key`、`api_base`和`model`。
