### ISSUE TITLE
在已有的GraphRAG项目里，如何放置chinese_text_splitter

### ISSUE THREAD

**Issue by popotang** [Airmomo/graphrag-practice-chinese#2]
您好，您提到：确保 chinese_text_splitter.py 文件位于正确的位置，使得 GraphRAG 能够找到并导入它。

在已有的GraphRAG项目里，比如graphrag-local-ollama这样的项目，splitter/chinese_text_splitter.py应该放到哪里呢，是把splitter放到根目录下还是放到graphrag目录或者其他什么地方？

**Comment by xfxsyz** [comment]
与分词器相关的，我用的是方法一，就是直接在tokens.py文件源代码注释了，换成作者您的了.
但是tokens模块被调用的时候，显示
ImportError: cannot import name 'run' from 'graphrag.index.verbs.text.chunk.strategies.tokens' (/root/miniconda3/envs/GraphRag/lib/python3.11/site-packages/graphrag/index/verbs/text/chunk/strategies/tokens.py)
与原模块之间没耦合，没有定义run函数

**Comment by Airmomo** [comment]
首先感谢 @popotang @xfxsyz 对本项目提出的疑问，我在刚刚对项目Readme内容以及部分文件（如`splitter/tokens.py` ）进行了补充上传，可以再重新参考一下。

@popotang ：
    在看到您的疑问之后，我去了解了一下 `graphrag-local-ollama` 这一项目，其项目是在 graphrag 基础上的改良，使 graphrag 能够通过调用 ollama 本地化部署的模型进行构建。
    在拉取 `graphrag-local-ollama` 后可以在其项目根目录中找到 graphrag/ 目录，这是其项目调用 graphrag 库的所在。所以要想 `graphrag-local-ollama` 中使用的分词器，只需要修改其 graphrag/ 中的分词器即可。其调用的分词器文件路径是 `graphrag-local-ollama/graphrag/index/verbs/text/chunk/strategies/tokens.py`，将它替换为本项目中的 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) 文件即可。
    至于其他已有的GraphRAG项目，您同样可以参考我这一思路进行修改。

@xfxsyz ：
    看到您提出的错误信息后，我才意识到我针对方法一的分词器文件忘了上传，Readme中对方法一的介绍也是有误的。
    方法一的分词方法是在 graphrag 项目中 tokens.py 的基础上，借鉴 `Langchain-ChatChat`项目中对中文字符的分词方法进行的改良。
    我已经补充上传了分词器文件 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) ，并相对应的修改了 Readme 中对方法一的介绍，请您再次参阅一下。

**方法 1:**
使用 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) 替换掉 python 依赖库中的 graphrag/index/verbs/text/chunk/strategies/tokens.py 即可。

**Comment by popotang** [comment]
> 首先感谢 @popotang @xfxsyz 对本项目提出的疑问，我在刚刚对项目Readme内容以及部分文件（如`splitter/tokens.py` ）进行了补充上传，可以再重新参考一下。
> 
> @popotang ： 在看到您的疑问之后，我去了解了一下 `graphrag-local-ollama` 这一项目，其项目是在 graphrag 基础上的改良，使 graphrag 能够通过调用 ollama 本地化部署的模型进行构建。 在拉取 `graphrag-local-ollama` 后可以在其项目根目录中找到 graphrag/ 目录，这是其项目调用 graphrag 库的所在。所以要想 `graphrag-local-ollama` 中使用的分词器，只需要修改其 graphrag/ 中的分词器即可。其调用的分词器文件路径是 `graphrag-local-ollama/graphrag/index/verbs/text/chunk/strategies/tokens.py`，将它替换为本项目中的 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) 文件即可。 至于其他已有的GraphRAG项目，您同样可以参考我这一思路进行修改。
> 
> @xfxsyz ： 看到您提出的错误信息后，我才意识到我针对方法一的分词器文件忘了上传，Readme中对方法一的介绍也是有误的。 方法一的分词方法是在 graphrag 项目中 tokens.py 的基础上，借鉴 `Langchain-ChatChat`项目中对中文字符的分词方法进行的改良。 我已经补充上传了分词器文件 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) ，并相对应的修改了 Readme 中对方法一的介绍，请您再次参阅一下。
> 
> **方法 1:** 使用 [splitter/tokens.py](https://github.com/Airmomo/graphrag-practice-chinese/blob/main/splitter/tokens.py) 替换掉 python 依赖库中的 graphrag/index/verbs/text/chunk/strategies/tokens.py 即可。

非常感谢作者详细的回复
