### ISSUE TITLE
方法二修改后能否在日志中找到成功的痕迹

### ISSUE THREAD

**Issue by dongkid** [Airmomo/graphrag-practice-chinese#5]
如题

**Comment by Airmomo** [comment]
@dongkid :

您好，首先感谢您对本项目的关注。在了解到你的问题之后，我再次运行了我的项目并查看GraphRAG的运行日志，并**没有发现替换文档切分策略中方法二提示成功的相关信息。**

为了验证是否替换成功，我删除了`setting.yaml`中方法二的配置选项，并从零开始运行了项目， 似乎在经过切分后得到了同样的`TextUnits`。对比后发现，只有使用方法一替换替换文档切分方法后才得到不同的`TextUnits`。**我开始意识到方法二是一个错误的方法，只有方法一才是生效的替换文档切分方法。**

在查阅官方文档中对配置项的详细介绍后，也并未找到对`splitter`的配置说明，即`setting.yaml`中并不支持`splitter`这一配置项，方法二是一个不应存在、错误的、无效的方法。

最后：
我修改了`Readme`，并删除了有关方法二的配置说明和配置文件`splitter/chinese_text_splitter`，我为该项目的严谨性感到抱歉，非常感谢你的反馈！
